name: Integracion continua
on:
  pull-request:
    branches: [develop]

jobs: 
  basic_ci:
    run-on: ubuntu-latest
    setps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn test